# Set prefix
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Split panes using | and -
bind | split-window -h
bind - split-window -v

# Sync panes
bind y set-window-option synchronize-panes on
bind u set-window-option synchronize-panes off

# Start numerotation with 1 instead of 0
setw -g base-index 1
set -g renumber-windows on

# Vim mode
setw -g mode-keys vi

# Display popup
bind p display-popup

# Increase tmux history from 2k to 3k lines
set -g history-limit 25000

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Disable oh-my-zsh automatic window renaming
set -g allow-rename off
set -g automatic-rename off
set -g set-titles off

# Change status line position 
# set-option -g status-position top
set-option -g status-position bottom 

# Options to make tmux more pleasant
set -g default-terminal "tmux-256color"

# Configure the catppuccin plugin
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #W "
set -g @catppuccin_window_current_text " #W "

# Make the status line pretty and add some modules
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_cpu}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"
set -agF status-right "#{E:@catppuccin_status_battery}"
set -g @catppuccin_window_default_fill "number"


# Load manually installed plugins 
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux
run ~/.config/tmux/plugins/tmux-cpu/cpu.tmux
run ~/.config/tmux/plugins/tmux-battery/battery.tmux
